
name: Use npm to build dist files, upload to itch

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  dist:

    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '25'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build

    - name: Download butler
      run: |
        curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
        unzip butler.zip -d butler
        chmod +x butler/butler
  

    - name: upload html to itch.io
      env:
        BUTLER_API_KEY: ${{ secrets.BUTLER_CREDS }}
      run: cd butler && ./butler push ../dist/ nsn/master-mason:html5

